### ISSUE TITLE
Add GitHub Action to build hook docs

### ISSUE THREAD

**Issue by dkotter** [10up/simple-google-news-sitemap#17]
In #14, we're adding proper docblocks to all of our hooks. Would be nice to take advantage of these even further by building out an automated hook docs site. See an example [here](https://github.com/10up/distributor/blob/develop/.github/workflows/build-docs.yml).

**Comment by jeffpaul** [comment]
@iamdharmesh mind picking this up when we're back in January and you've got some OSS time?
